server:
  port: 0 # Server information for embedded jetty
  url: http://16.16.16.16:8080 #the master base url used by the client to upload uber jar and data feed files

client:
  numberOfActors: 1 # Number of worker actors , controls the number of parallel simulation jobs you can run per process
  port: 0 # Port number for the actor system that host the worker actors
  role: "client" # The name of the role each actor uses (role1,role2...role5 etc)

client.accessKey: optional #optional access key for the partition
client.partitionName: public
client.className: optional
client.parameter: -Dusers=100 -Dramps=1 -DsimulationClass=com.walmart.store.gatling.simulation.BasicSimulation    #the simulation class is required
client.dataFeedPath: /Users/<user>/workspace/<path-to-data>/gatling-uber-example/data/search.csv # path to the data feed file
client.quiet: false
client.parallelism: 1
client.jarPath: /Users/<user>/workspace/<path-to-jar>/gatling-uber-example-1.0.2-SNAPSHOT.jar #path to uber jar
client.userName: Abiy
client.remoteArtifact: false
client.dataFeedFileName: search.csv #data feed file name
client.jarFileName: gatling-uber-example-1.0.2-SNAPSHOT.jar # jar file name
# Actor identifier  that is used to join the master/cluster
# update the host and port value to point to the cluster where the master is running on
akka:
  contact-points: "16.16.16.16:2551"

application.title: distGatling

logging.level.root: ERROR
logging.level.com.walmart.gatling: DEBUG
logging.level.com.walmart.gatling.Client: ERROR
