server:
  port: 0 # Server information for embedded jetty
  url: http://10.165.150.225:8080 #the master base url used by the client to upload uber jar and data feed files

client:
  numberOfActors: 1 # Number of worker actors , controls the number of parallel simulation jobs you can run per process
  port: 0 # Port number for the actor system that host the worker actors
  role: "client" # The name of the role each actor uses (role1,role2...role5 etc)

gatling.user: gatling
gatling.password: gatling
client.accessKey: optional #optional access key for the partition
client.partitionName: public
client.className: optional
client.parameter: -Dusers=100 -Dramps=1 -DsimulationClass=com.alh.store.gatling.simulation.BasicSimulation    #the simulation class is required
client.resourcesFeedPath: /Users/ahailem/workspace/dist-gatling-2/distGatling/gatling-uber-example/toupload.zip # path to the data feed file
client.quiet: false
client.parallelism: 1
client.jarPath: /Users/ahailem/workspace/dist-gatling-2/distGatling/gatling-uber-example/target/gatling-uber-example-1.0.2-SNAPSHOT.jar #path to uber jar
client.userName: Abiy
client.remoteArtifact: false
client.resourcesFeedFileName: toupload #data feed file name
client.jarFileName: gatling-uber-example-1.0.2-SNAPSHOT.jar # jar file name
# Actor identifier  that is used to join the master/cluster
# update the host and port value to point to the cluster where the master is running on
akka:
  contact-points: "10.165.150.225:2551"

application.title: distGatling

logging.level.root: ERROR
logging.level.com.alh.gatling: DEBUG
logging.level.com.alh.gatling.Client: ERROR
