FROM gatling:latest
ARG MASTER_SERVER_PORT=8080
ARG AKKA_PORT=2551

ENV MASTER_SERVER_PORT=${MASTER_SERVER_PORT}
ENV AKKA_PORT=${AKKA_PORT}
ENV GATLING_BUNDLE_PATH="/opt/gatling-charts-highcharts-bundle"
ENV DIST_GATLING_PATH="/usr/local/distGatling"

#use your own values here
ENV KUBERNETES_NAMESPACE="dist-gatling"
ENV GRAPHITE_ENABLE=true
ENV GRAPHITE_NAME="graphite-service"
ENV EXTERNAL_HOST=gatling-master.dist-gatling.svc.cluster.local


COPY gatling-*/*.sh ${DIST_GATLING_PATH}/
RUN chmod +x ${DIST_GATLING_PATH}/*.sh
COPY gatling-*/target/*.jar ${DIST_GATLING_PATH}/target/

EXPOSE ${MASTER_SERVER_PORT}
EXPOSE ${AKKA_PORT}
WORKDIR ${DIST_GATLING_PATH}


CMD ["/bin/bash", "-c", "cd ${DIST_GATLING_PATH} && ./master.sh -Dmaster.port=${AKKA_PORT} -Dkubernetes.kubernetes=true -Dserver.port=${MASTER_SERVER_PORT} -DCLUSTER_IP=`hostname -i` -DEXTERNAL_HOST=${EXTERNAL_HOST}"]