graphite:
    host: localhost
    port: 2003
    prefix: container
    frequency-in-seconds: 10000000

jersey:
    controller:
        packages: com.walmart

logging.level.root: INFO
logging.level.com.walmart: DEBUG

---

spring:
    profiles: testing
    
---

spring:
    profiles: integration

logging.level.com.walmart: INFO
    
---

spring:
    profiles: production

logging.level.com.walmart: INFO

