server:
  port: 8080

multipart:
  max-file-size: 10Mb

actor:
  numberOfActors: 1
  port: 2555
  role: "report"
  executerType: "script"
job:
  path: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7"
  logDirectory: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7/report/"
  command: "/bin/bash"
  artifact: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7/bin/{0}.sh"
logServer:
  port: 8080
  hostName: ""

file:
  repository: "/Users/ahailem/uploadspace/upload/"

graphite:
    host: localhost
    port: 2003
    prefix: gatling.master
    frequency-in-seconds: 10000000

jersey:
    controller:
        packages: com.walmart

logging.level.root: INFO
logging.level.com.walmart: DEBUG

---

spring:
    profiles: testing
    
---

spring:
    profiles: integration

logging.level.com.walmart: INFO
    
---

spring:
    profiles: production

logging.level.com.walmart: INFO

