server:
  port: 8080 # Server information for embedded jetty

security:
  username: "gatling"
  password: "gatling"

master:
  port: 2551 # Port of the master actor system
  name: backend #Name of the master actor
  primary: true
kubernetes:
  kubernetes: false #system should run on a kubernetes cluster

master.client.pool: 10
  # The number of active actors that can talk to the master via master singleton proxy

multipart:
  maxFileSize: 100Mb  # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
multipart.max-file-size: 100MB
multipart.max-request-size: 100MB
spring.http.multipart.max-file-size: 100Mb
spring.http.multipart.max-request-size: 100Mb
#Actor configurations for the actors used during report generation
actor:
  numberOfActors: 1
  port: 2555
  role: "report"
  executerType: "script"

job:
  path: "${GATLING_BUNDLE_PATH:'/Users/ahailem/workspace/gatling/gatling-charts-highcharts-bundle-3.0.2'}" # Path to the base directory where the gatling lib, simulation, data, and conf are stored
  logDirectory: "${DIST_GATLING_PATH:'/Users/ahailem/workspace/gatling/gatling-charts-highcharts-bundle-3.0.2'}/logs" # Base directory for logfiles(log/error and log/std)
  command: "/bin/bash" # Base command to run gatling.sh file
  artifact: "${GATLING_BUNDLE_PATH:'/Users/ahailem/workspace/gatling/gatling-charts-highcharts-bundle-3.0.2'}/bin/{0}.sh" # Path for the location of gatling.sh

file:
  repository: "${DIST_GATLING_PATH:'/Users/ahailem/workspace'}/gstore" # Base directory used as a temporary staging area for user file uploads(simulation files,conf,data files and lib files)

graphite: #Graphite configuration for master api metrics
    enable: "${GRAPHITE_ENABLE:false}"
    host: "${GRAPHITE_NAME:graphite-service}.${KUBERNETES_NAMESPACE:dist-gatling}.svc.cluster.local"
    port: 2003
    prefix: gatling.master
    frequency-in-seconds: 10

jersey:
    controller:
        packages: com.alh # Base package for jersey controllers for auto registration

logging.level.root: INFO
logging.level.com.alh.gatling: DEBUG

---

spring:
    profiles: testing
    
---

spring:
    profiles: integration

logging.level.com.alh.gatling: DEBUG
    
---

spring:
    profiles: production

logging.level.com.alh.gatling: DEBUG

