apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dist-gatling
  name: grafana-service
  labels:
    app: grafana
    component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      component: master
  template:
    metadata:
      name: grafana-service
      labels:
        app: grafana
        component: master
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
