server:
  port: 8090 # Server information for embedded jetty

actor:
  numberOfActors: 5 # Number of worker actors , controls the number of parallel simulation jobs you can run per process
  port: 2556 # Port number for the actor system that host the worker actors
  role: "public" # The name of the role each actor uses (role1,role2...role5 etc)
  executerType: "script"
job:
  path: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7" # Path to the base directory where the gatling simulation, data, and conf are stored
  logDirectory: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7/" # Base directory for logfiles(log/error and log/std)
  command: "/bin/bash" # Base command to run gatling.sh file
  artifact: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7/bin/{0}.sh" # Path for the location of gatling.sh
  jobDirectory: /Users/ahailem/workspace/gspace/

# Actor identifier  that is used to join the master/cluster
# update the host and port value to point to the cluster where the master is running on
akka:
  contact-points: "172.16.0.112:2551"

graphite:
    host: localhost
    port: 2003
    prefix: gatling-worker
    frequency-in-seconds: 10000

jersey:
    controller:
        packages: com.walmart # Base package for jersey controllers for auto registration

logging.level.root: INFO
logging.level.com.walmart.gatling: DEBUG

---

spring:
    profiles: testing
    
---

spring:
    profiles: integration

logging.level.com.walmart.gatling: INFO
    
---

spring:
    profiles: production

logging.level.com.walmart: INFO

