server:
  port: 8090

actor:
  numberOfActors: 5
  port: 2555
  role: "script"
  executerType: "script"
job:
  path: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7"
  logDirectory: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7/"
  command: "/bin/bash"
  artifact: "/Users/ahailem/workspace/gatling-charts-highcharts-bundle-2.1.7/bin/{0}.sh"
logServer:
  port: 8090
  hostName: ""
akka:
  contact-points: "akka.tcp://PerformanceSystem@127.0.0.1:2551/system/receptionist"
graphite:
    host: localhost
    port: 2003
    prefix: container
    frequency-in-seconds: 10000

jersey:
    controller:
        packages: com.walmart

logging.level.root: INFO
logging.level.com.walmart: DEBUG

---

spring:
    profiles: testing
    
---

spring:
    profiles: integration

logging.level.com.walmart: INFO
    
---

spring:
    profiles: production

logging.level.com.walmart: INFO

