server:
  port: 8090

actor:
  numberOfActors: 5
  port: 2555
  role: "script"
  executerType: "script"
job:
  path: "/Users/ahailemichael/workspace/jobs/"
  logDirectory: "/Users/ahailemichael/workspace/jobs/"
  command: "/bin/bash"
  artifact: "/Users/ahailemichael/workspace/jobs/artifact/script/{0}.sh"
logServer:
  port: 8083
  hostName: ""

graphite:
    host: localhost
    port: 2003
    prefix: container
    frequency-in-seconds: 10000

jersey:
    controller:
        packages: com.walmart

logging.level.root: INFO
logging.level.com.walmart: DEBUG

---

spring:
    profiles: testing
    
---

spring:
    profiles: integration

logging.level.com.walmart: INFO
    
---

spring:
    profiles: production

logging.level.com.walmart: INFO

